[project]
name = "mcp-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.6.0",
    "mcp[cli]>=1.11.0",
    "ollama>=0.5.1",
    "requests>=2.32.4",
]
